

global_filters: 
  min_cuda: 12.2
  max_cuda: 12.2
  min_nv_driver: 535
  max_nv_driver: 535
  min_vCPU: 5
  max_vCPU: 60
  priority_condition: vCPUs

contracts: 

  Machine1: 
    priority: 0
    image: pytorch/pytorch
    disk: 32
    task: jupyter_lab
    duration: 3000
    tunnel_port: 8888
    local_port: 8888
    start_command: ls
    end_command: uptime
    input_storage: "@relative_path/storage/input/Mch1" 
    output_storage: "@relative_path/storage/output/Mch1" 

  Machine2: 
    priority: 1
    image: pytorch/pytorch
    disk: 32
    task: jupyter_lab
    duration: 3000
    tunnel_port: 8889
    local_port: 8889
    start_command: ls
    end_command: uptime
    input_storage: "@relative_path/storage/input/Mch2" 
    output_storage: "@relative_path/storage/output/Mch2" 

   


      